### ISSUE TITLE
Penambahan fitur buat beatmap rank requests

### ISSUE THREAD

**Issue by troke12** [osu-datenshi/dap#4]
- [x] dikasi notes/reason kenapa beatmapnya ditolak
  - [x] reasonnya dikirim ke channel mapping discord
- [x] rework mark as done (kalau dah ketemu logikanya)

**Comment by ReiFan49** [comment]
mau db implementation

**Comment by ReiFan49** [comment]
Update status on "rework mark as done" with e92143b

**Comment by ReiFan49** [comment]
sek harusnya ini udah solve--- gak semuanya berhasil.. heran

**Comment by ReiFan49** [comment]
oke done. saatnya cabut bulu
